name: AWS OIDC Connect Demo
on:
  push:
    branches:
      - Development 
env:
  AWS_REGION : "us-east-1"
  AWS_BUCKET_NAME : "react-test-clientzr"
  AWS_ACCOUNT_ID : "733271263261"
  AWS_ROLE_NAME : "github-oidc-role-test"
permissions:
  id-token: write   
  contents: read   
jobs:
  DemoOIDC:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Development' 
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Print assumed role
        run: aws sts get-caller-identity

      - name: Print bucket
        run: aws s3 ls

  DemoBuild:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Development'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          role-session-name: cicdrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Started
        run: echo Build started on `date`

      - name: Build Started
        run: |
         echo Build started on `date`
         rm -rf package.lock.json && rm -rf node_modules
         rm -rf ./build
         npm install
         export CI=false && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 rm s3://${{ env.AWS_BUCKET_NAME }} --recursive && aws s3 cp ./build/ s3://${{ env.AWS_BUCKET_NAME }} --recursive